# webapp settings
spring:
  application:
    name: ${webapp.name:news}

spring.jpa:
  open-in-view: false
  properties:
    hibernate:
      generate_statistics: true
      jdbc.batch_size: 10

# tomcat settings
server:
  servlet:
    context-path: ${webapp.web-path:/news}

# logging settings
logging:
  pattern:
    level: "%5p ${HOSTNAME}"
  file:
    name: ${webapp.log-file:target/news.log}
  level:
    sql: debug
    '[org.springframework.web.servlet.DispatcherServlet]': debug
    '[org.springframework.web.client.RestTemplate]': debug
